export default {
  Bg: 'bg',
  StartBtn: 'startBtn',
  BackBtn: 'backBtn',
  RestartBtn: 'restartBtn',
  GameBg: 'gameBg',
  Trough: 'trough',
  Block0: 'block0',
  Block1: 'block1',
  Block2: 'block2',
  Block3: 'block3',
  Block4: 'block4',
  Block5: 'block5',
  Block6: 'block6',
  Block7: 'block7',
  Block8: 'block8',
  Block9: 'block9',
  Block10: 'block10',
  Block11: 'block11',
  Block12: 'block12',
  Block13: 'block13',
  Block14: 'block14',
  Block15: 'block15',
  MergeBlock1: 'mergeBlock1',
  MergeBlock2: 'mergeBlock2',
  MergeBlock3: 'mergeBlock3'
}
